set termguicolors
set background=light
colorscheme gruvbox
let g:lightline = {
      \ "colorscheme": "gruvbox",
      \ }

set clipboard=unnamedplus

set nobackup
set nowritebackup
set noswapfile

set mouse=a

let mapleader=" "

nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>/ :Rg<CR>
